name: Build and Deploy Angular + Node server to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
      
      # Build işleminden sonra, tüm gerekli dosyaları içeren klasörü deploy ediyoruz.
      # Azure, package.json'ı görecek, 'npm install --production' yapacak ve 'npm start' komutunu çalıştıracak.

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_85CFE3C6D8F546F28812125698516420 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21CDE7E8FE4B49DB840A0A007EA42D26 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6812244DF174C07869BD7AF25BB3448 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'staj-projem-frontend'
          package: . # Build edilmiş 'dist' klasörünü de içeren tüm paketi gönder.
